version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=k8-test
    ports:
      - 192.168.0.134:5432:5432

volumes:
  postgres_data: