apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django-deploy
spec:
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-container
          image: djangoimage
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: django-secrets
            - configMapRef:
                name: django-config-v3

---
apiVersion: v1
kind: Service
metadata:
  name: django-nodeport
spec:
  selector:
    app: django
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort:
    protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config-v3
  labels:
    app: django

data:
  DEBUG: "True"