apiVersion: v1
kind: Pod
metadata:
  name: django
spec:
  containers:
    - name: django-container
      image: djangoimage
      imagePullPolicy: Never
      envFrom:
        - secretRef:
            name: django-secrets
