apiVersion: v1
kind: Service
metadata:
  name: django-nodeport
spec:
  selector:
    app: django
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort:
    protocol: TCP